paritytrading/philadelphia

philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXSession.java, philadelphia/src/test/java/org/jvirtanen/philadelphia/FIXInitiatorTest.java, philadelphia/src/test/java/org/jvirtanen/philadelphia/Strings.java, philadelphia/src/test/java/org/jvirtanen/philadelphia/TestSession.java
Throw an exception upon an incoming message that is too long to fit into the receive buffer.
Fixes #15.
=> Handle too long message

philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXSession.java, philadelphia/src/test/java/org/jvirtanen/philadelphia/FIXConfigTest.java
Fixed
<pre>
java.lang.ArrayIndexOutOfBoundsException: 8
at org.jvirtanen.philadelphia.FIXValue.setString(FIXValue.java:240)
at org.jvirtanen.philadelphia.FIXSession.<init>(FIXSession.java:73)
at org.jvirtanen.philadelphia.FIXSession.<init>(FIXSession.java:127)
</pre>
if beginString is FIXT_1_1. (FIXT_1_1 + SOH = 9 bytes)
=> Fixed java.lang.ArrayIndexOutOfBoundsException

philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXSession.java, philadelphia/src/main/java/org/jvirtanen/philadelphia/package-info.java
Based on the model used in the NASDAQ SoupBinTCP 3.00 implementation in [Nassau](https://github.com/jvirtanen/nassau), add support for running data reception and transmission on different threads.
=> Support running data reception and transmission on different threads

philadelphia-fix42/src/main/java/com/paritytrading/philadelphia/fix42/FIX42Enumerations.java, philadelphia-fix43/src/main/java/com/paritytrading/philadelphia/fix43/FIX43Enumerations.java, philadelphia-fix44/src/main/java/com/paritytrading/philadelphia/fix44/FIX44Enumerations.java, philadelphia-fix50/src/main/java/com/paritytrading/philadelphia/fix50/FIX50Enumerations.java, philadelphia-fix50sp1/src/main/java/com/paritytrading/philadelphia/fix50sp1/FIX50SP1Enumerations.java, philadelphia-fix50sp2/src/main/java/com/paritytrading/philadelphia/fix50sp2/FIX50SP2Enumerations.java, scripts/generate
The symbolic names generated for enumerations are based on the symbolic names contained in the FIX Repository. The CxlRejResponseTo(434) values look as follows:
Value | Symbolic Name | Description
-|-|-
1 | `OrderCancelRequest` | Order Cancel Request
2 | `OrderCancel` | Order Cancel/Replace Request
The symbolic name `OrderCancel` for the value that indicates an Order Cancel/Replace Request message is confusing. Fix this by generating an alias with the symbolic name `OrderCancelReplaceRequest`.
Fixes #32.
=> Generate alias for CxlRejResponseTo(434) value

philadelphia/src/main/java/com/paritytrading/philadelphia/FIXSession.java
This is an issue / PR, the commits just make it clearer.
Every FIX message passes through the `FIXSession.MessageHandler.message` method, so it's on the critical path of most FIX applications. Unfortunately with 391 bytes in size it's the only method in Philadelphia larger than the 325 bytes default jvm hot method inline size.
The commit below reduces the size of the method to 315 bytes which allows inlining. Running the Philadelphia ping pong test before:
```
@ 275   com.paritytrading.philadelphia.FIXSession$MessageHandler::message (391 bytes)   hot method too big
```
after:
```
@ 275   com.paritytrading.philadelphia.FIXSession$MessageHandler::message (315 bytes)   inline (hot)
```
The removal of the check at line 553 should be fine as any message with 2 bytes message type is not the …
=> Reduce size of FIXSession.MessageHandler method

applications/client/src/main/java/com/paritytrading/philadelphia/client/TerminalClient.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/command/Commands.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/command/MessagesCommand.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/command/SleepCommand.java
- Add comment support: treat lines starting with `#` as comments.
- Add input file support: make it possible to run Philadelphia Terminal Client scripts.
- Improve `messages` command: add support for optional `index` parameter.
- Add `sleep` command: make the interpreter sleep for a number of milliseconds.
=> philadelphia-client: General improvements

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java
Like `FIXMessage#findField` but returns the index of the given tag.
=> philadelphia-core: Add FIXMessage#findIndex method

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXSession.java
- Rename `findIndex` to `indexOf` in the spirit of the standard library
- Rename `findField` to `valueOf` in the spirit of `indexOf` and `getValue`
=> philadelphia-core: Rename 'FIXMessage' methods

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXSession.java
Save one level of inline depth on send path as `channel.write(txBuffers)` effectively calls `channel.write(txBuffers, 0, txBuffers.length)`.
Tested running acceptor/initiator.
=> philadelphia-core: Avoid unnecessary method call on socket write

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java
This is useful when working with message templates for messages with variable number of fields (e.g. due to repeating groups): the initial fixed-length portion will constitute the message template while the
subsequent variable-length portion will be built from scratch every time.
=> philadelphia-core: Make it possible to set number of fields

libraries/core/src/main/java/com/paritytrading/philadelphia/FIX.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java
- Use preformatted byte arrays for the BeginString(8), BodyLength(9), and CheckSum(10) tags
- When sending a message, instead of formatting the entire message header, only format the BodyLength(9) value
=> philadelphia-core: Simplify message header and trailer handling

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java
Remove explicit `null` checks. This reduces the bytecode sizes from 45 bytes to 27 bytes, which is under HotSpot's default maximum inline size of 35 bytes.
**Note.** This is an API change as these methods will no longer throw an `InvalidStateException` but might throw a `NullPointerException` instead. Both being unchecked exceptions, I would argue that this is a backwards compatible API change. Thoughts?
=> philadelphia-core: Optimize 'FIXConnection#update' and 'FIXConnection#updateCompID'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTimestamps.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
Using a buffer is roughly 16% faster than working with the `StringBuilder` directly.
~**Note.** This is an API change as this method will no longer be thread-safe. However, I would argue that this does not require bumping the major version number. Thoughts?~
=> philadelphia-core: Optimize 'FIXTimestamps.append'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java
After sending a TestRequest(1) message, consider the procedure successful on receiving any data from the other party, not just a Heartbeat(0) message.
The purpose of this change is to separate the keep-alive mechanism from the handling of administrative messages, making it easier to provide a way for applications to implement their own handling of administrative messages.
=> philadelphia-core: Simplify keep-alive mechanism

applications/generate/philadelphia/repository.py, libraries/fix42/src/main/java/com/paritytrading/philadelphia/fix42/FIX42Enumerations.java, libraries/fix43/src/main/java/com/paritytrading/philadelphia/fix43/FIX43Enumerations.java, libraries/fix44/src/main/java/com/paritytrading/philadelphia/fix44/FIX44Enumerations.java, libraries/fix50/src/main/java/com/paritytrading/philadelphia/fix50/FIX50Enumerations.java, libraries/fix50sp1/src/main/java/com/paritytrading/philadelphia/fix50sp1/FIX50SP1Enumerations.java, libraries/fix50sp2/src/main/java/com/paritytrading/philadelphia/fix50sp2/FIX50SP2Enumerations.java, libraries/fixt11/src/main/java/com/paritytrading/philadelphia/fixt11/FIXT11Enumerations.java
When reading field values from the FIX Repository, change the type from `String` to `char` if all field values have the length of one character. Working with primitive `char` values is more efficient than working with `String` objects in Java.
**Note.** This is a breaking change and scheduled for Philadelphia 2.0.0.
=> philadelphia-generate: Improve enumeration handling

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXCheckSums.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTags.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTimestamps.java
- Remove `FIXCheckSums` from public interface
- Remove `FIXTags` from public interface
- Remove `FIXTimestamps` from public interface
In addition to being used by the library internals, these utility classes are currently part of the public interface. Clean up the public interface and enable further optimizations by making these classes internal.
**Note.** This is a breaking change and scheduled for Philadelphia 2.0.0.
=> philadelphia-core: Clean up public interface

applications/client/pom.xml, applications/client/src/main/java/com/paritytrading/philadelphia/client/TerminalClient.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/command/Commands.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/command/HelpCommand.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/command/MessagesCommand.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/command/WaitCommand.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/message/Message.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/message/Messages.java, pom.xml
The usage of Eclipse Collections in Philadelphia precedes Java 8. Replace Eclipse Collections with the `java.util.stream` package.
=> Remove Eclipse Collections

applications/generate/pom.xml, applications/generate/setup.py, pom.xml, scripts/archive.txt
Add a Maven module for Philadelphia Code Generator. Make Philadelphia Code Generator's version track Philadelphia's version by reading the value from `pom.xml` in `setup.py`.
=> philadelphia-generate: Improve version handling

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageParser.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java
It is just an alias for `FIXValue#asInt`.
**Note.** This is a breaking change and scheduled for Philadelphia 2.0.0.
=> philadelphia-core: Remove 'FIXValue#asCheckSum'

applications/generate/philadelphia/java.py, libraries/fix42/src/main/java/com/paritytrading/philadelphia/fix42/FIX42Enumerations.java, libraries/fix42/src/main/java/com/paritytrading/philadelphia/fix42/FIX42MsgTypes.java, libraries/fix42/src/main/java/com/paritytrading/philadelphia/fix42/FIX42Tags.java, libraries/fix43/src/main/java/com/paritytrading/philadelphia/fix43/FIX43Enumerations.java, libraries/fix43/src/main/java/com/paritytrading/philadelphia/fix43/FIX43MsgTypes.java, libraries/fix43/src/main/java/com/paritytrading/philadelphia/fix43/FIX43Tags.java, libraries/fix44/src/main/java/com/paritytrading/philadelphia/fix44/FIX44Enumerations.java, libraries/fix44/src/main/java/com/paritytrading/philadelphia/fix44/FIX44MsgTypes.java, libraries/fix44/src/main/java/com/paritytrading/philadelphia/fix44/FIX44Tags.java, libraries/fix50/src/main/java/com/paritytrading/philadelphia/fix50/FIX50Enumerations.java, libraries/fix50/src/main/java/com/paritytrading/philadelphia/fix50/FIX50MsgTypes.java, libraries/fix50/src/main/java/com/paritytrading/philadelphia/fix50/FIX50Tags.java, libraries/fix50sp1/src/main/java/com/paritytrading/philadelphia/fix50sp1/FIX50SP1Enumerations.java, libraries/fix50sp1/src/main/java/com/paritytrading/philadelphia/fix50sp1/FIX50SP1MsgTypes.java, libraries/fix50sp1/src/main/java/com/paritytrading/philadelphia/fix50sp1/FIX50SP1Tags.java, libraries/fix50sp2/src/main/java/com/paritytrading/philadelphia/fix50sp2/FIX50SP2Enumerations.java, libraries/fix50sp2/src/main/java/com/paritytrading/philadelphia/fix50sp2/FIX50SP2MsgTypes.java, libraries/fix50sp2/src/main/java/com/paritytrading/philadelphia/fix50sp2/FIX50SP2Tags.java, libraries/fixt11/src/main/java/com/paritytrading/philadelphia/fixt11/FIXT11Enumerations.java, libraries/fixt11/src/main/java/com/paritytrading/philadelphia/fixt11/FIXT11MsgTypes.java, libraries/fixt11/src/main/java/com/paritytrading/philadelphia/fixt11/FIXT11Tags.java
Add a comment to the output files of Philadelphia Code Generator indicating that they have been automatically generated.
=> philadelphia-generate: Add comment to output files

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java
The `FIXValue#set` method fails if the specified value container contains a value at a non-zero offset. Fix this.
=> philadelphia-core: Fix 'FIXValue#set'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageParser.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
Minor performance improvement for checksum calculations by replacing power of two modulo operations with bitwise AND.
JIT might or might not do this optimisation eventually but order entry is frequently not entirely hot so this should be a clear and simple improvement.
=> philadelphia-core: Replace modulo with power of two bitmask

applications/client/src/main/java/com/paritytrading/philadelphia/client/TerminalClient.java
Apply command completion only on the first token.
Fixes #103.
=> philadelphia-client: Fix command completion

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java
When reading a date value, only set the date fields, not the time fields. `FIXValue#asTimeOnly` already works in this manner.
This makes it possible to combine the outputs of `FIXValue#asDate` and `FIXValue#asTimeOnly`. These data types are used in fields such as MDEntryDate(272) and MDEntryTime(273).
=> philadelphia-core: Fix 'FIXValue#asDate'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java
When checking for SequenceReset(4), check the first byte of the MsgType(35) value before checking its length. This avoids one conditional check for most messages.
Note that the length of the MsgType(35) value could in principle be zero. In that case, "the first byte of the value" is actually the SOH character.
=> philadelphia-core: Improve MsgType(35) handling

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
In `FIXValue#asDate`, setting the date components one by one surprisingly takes only roughly 45% of the time it takes to set them all at once. In `FIXValue#asTimestamp`, too, setting the date and time components one by one gives a modest performance improvement as opposed to setting them all at once.
=> philadelphia-core: Optimize Joda-Time operations

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
Before manipulating the message header, `ByteBuffer#clear` must be invoked to reset the buffer's limit back to its capacity. This call was erroneously removed in the commit f68f0c2defc32be63ee0e800e50d953bf7d3e366.
=> philadelphia-core: Fix message header handling

applications/client/src/main/java/com/paritytrading/philadelphia/client/SendCommand.java
Make it possible to send a message containing a field with whitespace characters.
=> philadelphia-client: Fix 'send' command

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
- Use `x` and `y` as the primary and secondary variables for the value
- Use `i` and `j` as the index variables
=> philadelphia-core: Clean up 'FIXValue' operations

applications/client/etc/example.conf, applications/client/etc/example.txt, scripts/archive.txt
Add an example script that can be used to interact with Philadelphia Example Acceptor.
=> philadelphia-client: Add example script

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageParser.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
It will be removed in Philadelphia 2.0.0.
=> philadelphia-core: Mark 'FIXValue#asCheckSum' as deprecated

libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java
The method `FIXValue#asCheckSum` has been deprecated. Suppress deprecation warnings in the unit tests.
=> philadelphia-core: Suppress deprecation warnings

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageParser.java, tests/perf-test/src/main/java/com/paritytrading/philadelphia/FIXMessageParserBenchmark.java
Having the incoming CheckSum(10) check in a separate method makes message parsing 9.6% faster in the performance test when the incoming CheckSum(10) check is disabled and 3.7% faster when it is enabled.
=> philadelphia-core: Improve 'FIXMessageParser'

libraries/core/src/test/java/com/paritytrading/philadelphia/ByteBuffers.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXConnectionStatus.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXMessages.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FixedClock.java, libraries/core/src/test/java/com/paritytrading/philadelphia/Strings.java, libraries/core/src/test/java/com/paritytrading/philadelphia/TestConnection.java, libraries/core/src/test/java/com/paritytrading/philadelphia/TestMessageParser.java, libraries/core/src/test/java/com/paritytrading/philadelphia/TestMessages.java
Remove superfluous `public` modifiers.
=> philadelphia-core: Clean up test classes

applications/client/src/main/java/com/paritytrading/philadelphia/client/TerminalClient.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIX.java, tests/perf-test/src/main/java/com/paritytrading/philadelphia/FIXTagsBenchmark.java
When possible, use an array initializer instead of a full-blown array creation expression.
=> Clean up array initializers

applications/client/src/main/java/com/paritytrading/philadelphia/client/WaitCommand.java
The `wait` command looks at received messages at an interval, stopping if the last received message has a matching MsgType(35) value. If two or more messages are received within one interval, the `wait` command may miss a matching MsgType(35) value and erroneously continue waiting.
Fix the `wait` command so that it looks at all received messages since being issued.
Closes #117.
=> philadelphia-client: Fix 'wait' command

applications/client/pom.xml, examples/acceptor/pom.xml, examples/initiator/pom.xml, libraries/core/README.md, libraries/core/pom.xml
Currently, Philadelphia Core depends on Joda-Time 2.10.5. This means that any application that has a dependency on Philadelphia Core also has a transitive dependency on Joda-Time 2.10.5.
Replace the transitive Joda-Time 2.10.5 dependency with a Joda-Time 2.x dependency. This makes it possible for applications to manage their Joda-Time 2.x and Philadelphia Core dependencies independently.
This also means that applications that use Philadelphia Core but do not yet use Joda-Time 2.x need to add a dependency on Joda-Time 2.x as well.
=> philadelphia-core: Remove transitive Joda-Time dependency

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
This fixes a performance regression in the method by reverting the changes done since the 1.1.1 release.
In the commit 51444a7 the method was changed so that it sets the fields one by one rather than all at once. This made the method 3.8x slower.
=> philadelphia-core: Fix 'FIXValue#asTimestamp'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
Set the fields all at once rather than one by one. This makes the method 33% faster.
=> philadelphia-core: Improve 'FIXValue#asTimeOnly'

applications/generate/pom.xml
As with the other executables, such as Philadelphia Terminal Client, skip the Maven deployment of Philadelphia Code Generator. In practice this means that this POM will no longer be uploaded to the Central Repository as a part of a Philadelphia release.
=> philadelphia-generate: Skip Maven deployment

libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java
The following test cases rely on the side effect of an attempt to read an incomplete value from a buffer partially populating the value container:
- `FIXValueTest#asDate`
- `FIXValueTest#asTimeOnlyWithMillis`
- `FIXValueTest#asTimeOnlyWithoutMillis`
- `FIXValueTest#asTimestampWithMillis`
- `FIXValueTest#asTimestampWithoutMillis`
Fix the test cases so that they actually read a complete value.
=> philadelphia-core: Fix tests

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
Change an argument type and eliminate a variable to decrease the bytecode size of the method from 44 bytes to 31 bytes, which is within HotSpot's default maximum inline size of 35 bytes.
=> philadelphia-core: Optimize 'FIXValue#setDigits'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java
Extend the existing functionality of `FIXMessage#valueOf` and `FIXMessage#indexOf` with a second argument specifying the index to start looking from.
This is useful when a message has the same tag multiple times with different values and one wishes to cycle through them.
=> philadelphia-core: Get first tag or value starting from given index

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTimestamps.java
This decreases the bytecode size of the method from 36 to 28 bytes, which is within HotSpot's default maximum inline size of 35 bytes.
=> philadelphia-core: Optimize 'FIXTimestamps#setDigits'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
Optimize handling of positive numbers at the expense of negative numbers. This decreases the bytecode sizes of the methods as follows:
Method | Before | After
-|-|-
`setInt` | 102 | 79
`setFloat` | 177 | 161
The impact on the microbenchmarks is negligible.
=> philadelphia-core: Optimize 'FIXValue#setInt' and 'FIXValue#setFloat'

.github/workflows/test.yml, applications/generate/README.md, scripts/generate, scripts/generate-fixlatest
Python 3.5 has reached end-of-life.
=> philadelphia-generate: Require Python 3.6 or newer

scripts/generate
Make the script work not only with absolute paths but with relative paths as well.
=> scripts: Fix 'generate' script

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java
Remove the pipe character (`|`) from the `FIXValue#toString()` return value. As this means that the return value of this method will be equal to the return value of the `FIXValue#asString()` method, remove the `FIXValue#toString(StringBuilder)` method as it becomes effectively a duplicate of the `FIXValue#asString(StringBuilder)` method.
Philadelphia uses the pipe character as a human-readable stand-in for the non-printable SOH character, which terminates a value in the FIX protocol. Although it is a part of the internal data representation in the `FIXValue` class, I feel that aligning the `toString` method to the `asString` method makes much more sense for most use cases of this method.
As this method was added after the most recent release, 1.2.0, this change will have no impact on …
=> philadelphia-core: Improve 'FIXValue#toString'

scripts/format-perf-test
It formats Philadelphia Performance Test results as [GitHub Flavored Markdown (GFM)](https://github.github.com/gfm/) for the regression test in the release process.
The raw output looks like this:
```markdown
Benchmark                        | Baseline | Candidate | Status
---------------------------------|---------:|----------:|:-----------------:
`FIXCheckSumsBenchmark.baseline` |     1.00 |      1.00 | :white_check_mark:
`FIXCheckSumsBenchmark.sum`      |     1.00 |      0.95 | :white_check_mark:
```
The formatted output looks like this:
Benchmark                        | Baseline | Candidate | Status
---------------------------------|---------:|----------:|:-----------------:
`FIXCheckSumsBenchmark.baseline` |     1.00 |      1.00 | :white_check_mark:
`FIXCheckSumsBenchmark.sum` …
=> scripts: Add 'format-perf-test'

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTimestamps.java
Although the original change decreases the bytecode size of the method from 36 to 28 bytes, which is within HotSpot's default maximum inline size of 35 bytes, this appears to cause a 1-2% performance regression when HotSpot has fully optimized this code. Fix this by removing the bytecode optimization.
This reverts commit 1571bf60bbba825fd216794a3d09bb0f41092a29.
=> philadelphia-core: Remove 'FIXTimestamps.setDigits' optimization

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
Although the original change decreases the bytecode size of the method from 39 to 31 bytes, which is within HotSpot's default maximum inline size of 35 bytes, this appears to cause a 1-2% performance regression when HotSpot has fully optimized this code. Fix this by removing the bytecode optimization.
This reverts commit 64c68f47d57e833613a531cc7429a6d59ec23f3a.
=> philadelphia-core: Remove 'FIXValue#setDigits' optimization

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
The value 0 for the EndSeqNo(16) field in a ResendRequest(2) message should represent infinity and correspond to all subsequent messages after the message referred to by the BeginSeqNo(7) field.
As noticed by @mhartememx, the handling for this value is currently broken. Fix this.
=> philadelphia-core: Fix EndSeqNo(16) handling

scripts/format-perf-test
Embarrassingly, the baseline and candidate results are mixed up. Fix this.
=> scripts: Fix 'format-perf-test' script

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTimestamps.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
Due to an [error in the `format-perf-test` script](https://github.com/paritytrading/philadelphia/pull/186), performance improvements got misclassified as performance regressions and subsequently removed. Restore these optimizations.
This reverts commits 26489ce and a1197f5.
=> philadelphia-core: Restore 'FIXTimestamps.setDigits' and 'FIXValue#setDigits' optimizations

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageOverflowException.java
This exception is thrown both when the message length exceeds the capacity of the receive buffer as well as when the number of fields exceeds the capacity of a message container.
=> philadelphia-core: Fix 'FIXMessageOverflowException' documentation

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXCheckSums.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTags.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTimestamps.java
These classes were originally public in order to expose them to the performance test, which itself used to be in another package. Make them package-private as a part of the next major version, Philadelphia 2.0.0, to clean up the public interface of the library.
=> philadelphia-core: Make 'FIXCheckSums', 'FIXTags', and 'FIXTimestamps' package-private

applications/client/src/main/java/com/paritytrading/philadelphia/client/Message.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/TestMessageParser.java, tests/perf-test/src/main/java/com/paritytrading/philadelphia/FIXValueBenchmark.java
To make it easier to work with `FIXValue` objects, make the class implement the [`CharSequence`](https://docs.oracle.com/javase/8/docs/api/java/lang/CharSequence.html) interface. Furthermore, change the result type of `FIXValue#asString()` from `String` to `CharSequence` and avoid memory allocation. Finally, remove both `FIXValue#asString(Appendable)` as well as `FIXValue#asString(StringBuilder)` methods as redundant as they can now be replaced by [`Appendable#append(CharSequence)`](https://docs.oracle.com/javase/8/docs/api/java/lang/Appendable.html#append-java.lang.CharSequence-) and [`StringBuilder#append(CharSequence)`](https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html#append-java.lang.CharSequence-).
=> philadelphia-core: Make 'FIXValue' into 'CharSequence'

scripts/generate-orchestra, scripts/generate-repository
Make them work either with an absolute path or a relative path to the input file or the input directory, respectively.
=> scripts: Fix 'generate-orchestra' and 'generate-repository' scripts

applications/generate/.pylintrc
=> philadelphia-generate: Remove Pylint configuration

applications/generate/philadelphia/generate.py, applications/generate/philadelphia/java.py, applications/generate/philadelphia/model.py, applications/generate/philadelphia/orchestra.py, applications/generate/philadelphia/quickfix.py, applications/generate/philadelphia/repository.py, applications/generate/philadelphia/source.py, libraries/fixlatest/src/main/java/com/paritytrading/philadelphia/fixlatest/FIXLatestEnumerations.java
In addition to associating an enumeration with a primary field, make it possible to associate it with secondary fields as well. Use this feature in the FIX Orchestra input source.
=> philadelphia-generate: Improve FIX Orchestra support

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXMessageTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java, tests/perf-test/src/main/java/com/paritytrading/philadelphia/FIXValueBenchmark.java
Split `FIXValue#setTimeOnly()` into two methods:
- `FIXValue#setTimeOnlyMillis()`
- `FIXValue#setTimeOnlySecs()`
Split `FIXValue#setTimestamp()` into two methods:
- `FIXValue#setTimestampMillis()`
- `FIXValue#setTimestampSecs()`
=> philadelphia-core: Clean up 'FIXValue#setTimeOnly()' and 'FIXValue#setTimestamp()'

applications/generate/philadelphia/quickfix.py
Do not try to generate enumerations based on `field` elements that do not contain any `value` elements.
In addition, as with the FIX Repository, update the enumeration type from `char` to `String` if any of the enumeration values has a length greater than one.
=> philadelphia-generate: Fix QuickFIX support

applications/client/pom.xml, examples/acceptor/pom.xml, examples/initiator/pom.xml, libraries/core/README.md, libraries/core/pom.xml, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXTimestamp.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXMessageTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXTimestampTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java, pom.xml, tests/perf-test/pom.xml, tests/perf-test/src/main/java/com/paritytrading/philadelphia/FIXValueBenchmark.java
Replace `MutableDateTime` usage with a `FIXTimestamp` class, and remove the Joda-Time 2.x dependency. In addition to removing the dependency, this improves the performance significantly.
Benchmark |                     Baseline |Candidate
------------------------------|--------|---------
FIXValueBenchmark.asDate         |  1.00 |     0.46
FIXValueBenchmark.asTimeOnly   |    1.00 |     0.38
FIXValueBenchmark.asTimestamp |     1.00 |     0.49
FIXValueBenchmark.setDate          |1.00  |    0.68
FIXValueBenchmark.setTimeOnly   |   1.00 |     0.44
FIXValueBenchmark.setTimestamp |    1.00 |     0.31
Note that the benchmarks above include both parsing or formatting the values to or from bytes as well as converting the timestamps to or from numbers of milliseconds from the epoch.
=> philadelphia-core: Add 'FIXTimestamp'

libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
The test uses blocking I/O to ensure that the implementation under test receives Heartbeat(0) messages. This is because a Heartbeat(0) message does not have a callback unlike, for example, a Logon(A) message.
Make the test simpler by replacing blocking I/O with a MsgSeqNum(34) check. Although a Heartbeat(0) message does not invoke a callback, it still increments the MsgSeqNum(34) value.
=> philadelphia-core: Clean up test

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
Do not increment the outgoing MsgSeqNum(34) value when sending a SequenceReset(4) message.
Fixes #231.
=> philadelphia-core: Fix MsgSeqNum(34) handling on SequenceReset(4)

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
Handle a Logout(5) message with too low MsgSeqNum(34) value, but still send a ResendRequest(2) message when receiving a Logout(5) message with too high MsgSeqNum(34) value.
Supersedes #228.
=> philadelphia-core: Improve Logout(5) handling

.github/workflows/python.yml, applications/generate/README.md, scripts/generate-orchestra, scripts/generate-repository
Python 3.6 has reached end-of-life.
=> philadelphia-generate: Require Python 3.7 or newer

applications/client/src/main/java/com/paritytrading/philadelphia/client/Messages.java, applications/client/src/main/java/com/paritytrading/philadelphia/client/Session.java, examples/acceptor/src/main/java/com/paritytrading/philadelphia/acceptor/Session.java, examples/initiator/src/main/java/com/paritytrading/philadelphia/initiator/Initiator.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusListener.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXConnectionStatus.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorPipeChannelTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorSocketChannelTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/PipeChannel.java, libraries/core/src/test/java/com/paritytrading/philadelphia/TestConnection.java
Raising this pull request as a proposal for issue #236 
The change changes the raw signature of `FIXConnection.getChannel()` in backwards incompatible way. The migration fix for existing usages would be to either specify generic parameter or to downcast.
I have made the `FIXInitiatorTest` abstract and pushed the current implementation into a `FIXInitiatorSocketTest` subclass. I have also added `FIXInitiatorPipeTest`  as an example of how to use the new functionality.
=> Allow to pass other channel types

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/package-info.java
Refer to underlying channels rather than underlying socket channels everywhere.
Document the type bounds for the underlying channel type in the generic constructor, and retain a reference to [`SocketChannel`](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/SocketChannel.html), still the most common underlying channel type, in the Javadoc comment.
Prefer the terms "inbound" and "outbound" to the terms "RX" and "TX" in the API.
=> philadelphia-core: Improve 'FIXConnection' interface

applications/client/pom.xml, examples/acceptor/pom.xml, examples/initiator/pom.xml, pom.xml, tests/perf-test/pom.xml
The plugin behavior has changed between the previously used version, 3.2.1, and the currently used version, 3.3.0.
=> Fix 'maven-shade-plugin' configuration

pom.xml, tests/perf-test/pom.xml
Do not minimize JARs anymore. This has the following small impact on the executable JAR sizes:
Name                   | Size Difference(KiB)
-----------------------|--------------------:
`philadelphia-client`    |                  +42
`philadelphia-acceptor`  |                   +8
`philadelphia-initiator` |                 +104
`philadelphia-perf-test` |                    0
=> Clean up 'maven-shade-plugin' configuration

pom.xml
The package name JMH uses for generated code has changed between JMH 1.23 and JMH 1.35.
=> Fix 'maven-javadoc-plugin' configuration

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConfig.java
Retain backwards compatibility.
=> philadelphia-core: Restore 'FIXConfig.Builder' constructor

applications/client/src/main/java/com/paritytrading/philadelphia/client/Session.java, examples/acceptor/src/main/java/com/paritytrading/philadelphia/acceptor/Session.java, examples/initiator/src/main/java/com/paritytrading/philadelphia/initiator/Initiator.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXConfigTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
Current initialization with 0 leads to potential messages before the Logon message.
Fixes #301
=> Proper initialization of lastTxMillis and lastRxMillis.

pom.xml
Only output warnings and errors from the plugin.
=> Improve 'maven-javadoc-plugin' configuration

applications/client/src/main/java/com/paritytrading/philadelphia/client/Messages.java, examples/acceptor/src/main/java/com/paritytrading/philadelphia/acceptor/Session.java, examples/initiator/src/main/java/com/paritytrading/philadelphia/initiator/Initiator.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusListener.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXHeartbeatTimeoutException.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXConnectionStatus.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
Replace the `FIXConnectionStatusListener#heartbeatTimeout()` method with a `FIXHeartbeatTimeoutException` class. The purpose of this change is to separate heartbeat timeout handling, which is implemented in the `FIXConnection` class, from other administrative message handling. This is in preparation of making it possible for applications to implement their own administrative message handling.
=> philadelphia-core: Refactor heartbeat timeout handling

libraries/core/src/main/java/com/paritytrading/philadelphia/FIX.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusHandler.java
Make it possible for applications to implement their own administrative message handling.
=> philadelphia-core: Make 'FIXConnectionStatusListener' optional

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConfig.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusHandler.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXConfigTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
For brevity, prefer "in" instead of "incoming" and "out" instead of "outgoing" in method names. Align some method parameter names with corresponding instance variable names.
=> philadelphia-core: Clean up terminology

examples/initiator/src/main/java/com/paritytrading/philadelphia/initiator/Initiator.java
Ensure that we only send as many orders as requested to avoid the application terminating the TCP connection while having outstanding NewOrderSingle(D) requests pending ExecutionReport(8) responses.
=> philadelphia-initiator: Fix message handling

libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java
The test is currently not deterministic, as the receive loop may be exited before the acceptor has received the Logout(5) message. Make the test deterministic by having individual receive loops for the initiator and the acceptor.
=> philadelphia-core: Fix 'FIXInitiatorTest#receiveLogonWithTooLowMsgSeqNum()'

CHANGELOG.md, UPGRADE-2.1.0.md, libraries/core/pom.xml, libraries/fix40/pom.xml, libraries/fix41/pom.xml, libraries/fix42/pom.xml, libraries/fix43/pom.xml, libraries/fix44/pom.xml, libraries/fix50/pom.xml, libraries/fix50sp1/pom.xml, libraries/fix50sp2/pom.xml, libraries/fixlatest/pom.xml, libraries/fixt11/pom.xml, pom.xml, scripts/archive.txt
Introduce minimal Java module support by specifying module names for all libraries corresponding to their package names.
=> Specify Java module names

CHANGELOG.md, UPGRADE-2.1.0.md, applications/client/src/main/java/com/paritytrading/philadelphia/client/TerminalClient.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIX.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConfig.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusHandler.java, libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXConfigTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXMessageParserTest.java, libraries/core/src/test/java/com/paritytrading/philadelphia/FIXMessageTest.java
Simplify configuration by introducing the concept of message capacity: the number of fields a message container can hold. A message container starts at its initial message capacity and grows when necessary until it reaches its maximum message capacity.
This change introduces one conditional statement on the fast path, in the `FIXMessage#addField()` method. Based on the performance test, this has no measurable impact. Note that for the best performance, an application should still set the initial and the maximum message capacity to the same value, as growing a message container will have discernible effect.
=> philadelphia-core: Introduce message capacity

pom.xml
Specify `-proc:full` on Java 21 to silence a compilation warning.
=> Improve 'maven-compiler-plugin' configuration

.github/workflows/python.yml, applications/generate/README.md, documentation/generate.md, documentation/release.md, scripts/generate-orchestra, scripts/generate-repository
Python 3.8 has reached end-of-life.
=> philadelphia-generate: Require Python 3.9 or newer

.github/dependabot.yml
=> Ignore upgrade to Checkstyle 11
