philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXConfig.java
philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXSession.java

Addressing #5 with defaults as before.

Make rx/tx buffer capacity configurable via FIXConfig

---

scripts/generate

To help in adding support for additional FIX protocol versions, implement code generation based on the [FIX Repository](http://www.fixtradingcommunity.org/pg/structure/tech-specs/fix-tools/fix-repository).

Implement code generation

---

philadelphia-acceptor/src/main/java/org/jvirtanen/philadelphia/acceptor/Session.java
philadelphia-initiator/src/main/java/org/jvirtanen/philadelphia/initiator/Initiator.java
philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXSession.java
philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXStatusListener.java
philadelphia/src/test/java/org/jvirtanen/philadelphia/FIXStatus.java

As discussed in #10 
Ran tests and initiators/acceptors for ping pong test.

Accessing FIXSession inside FIXStatusListener

---

README.md
philadelphia-client/README.md
philadelphia-client/etc/devel.conf
philadelphia-client/pom.xml
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/Session.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/TerminalClient.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/command/Command.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/command/CommandException.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/command/Commands.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/command/ExitCommand.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/command/HelpCommand.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/command/MessagesCommand.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/command/SendCommand.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/message/Field.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/message/Message.java
philadelphia-client/src/main/java/org/jvirtanen/philadelphia/client/message/Messages.java
philadelphia-client/src/test/java/org/jvirtanen/philadelphia/client/message/FieldTest.java
philadelphia-client/src/test/java/org/jvirtanen/philadelphia/client/message/MessageTest.java
pom.xml

It is a simple console application for interacting with a FIX acceptor.

Add terminal client

---

philadelphia-perf-test/pom.xml
pom.xml

Minimize shaded JARs

---

philadelphia/src/main/java/com/paritytrading/philadelphia/FIXSession.java
philadelphia/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java

Expose next incoming and outgoing MsgSeqNum(34)

---

philadelphia/src/main/java/com/paritytrading/philadelphia/FIXSession.java

Expose SenderCompID(49) and TargetCompID(56)

---

philadelphia/src/main/java/com/paritytrading/philadelphia/FIXConfig.java
philadelphia/src/main/java/com/paritytrading/philadelphia/FIXMessageParser.java
philadelphia/src/main/java/com/paritytrading/philadelphia/FIXSession.java
philadelphia/src/test/java/com/paritytrading/philadelphia/FIXMessageParserTest.java

Make incoming CheckSum(10) check optional

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConfig.java

philadelphia-core: Add toString method to FIXConfig

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
tests/perf-test/src/main/java/com/paritytrading/philadelphia/perf/FIXValueBenchmark.java

- Use `System.arraycopy` to set value
- Add method to `perf-test` as was not included in tests yet

philadelphia-core: Use System.arraycopy to set FIXValue

---

applications/client/src/main/java/com/paritytrading/philadelphia/client/command/MessagesCommand.java
checkstyle.xml
pom.xml
tests/perf-test/src/main/java/com/paritytrading/philadelphia/perf/FIXMessageBenchmark.java
tests/perf-test/src/main/java/com/paritytrading/philadelphia/perf/FIXTagsBenchmark.java

You can run it as follows:
```
mvn compile checkstyle:check
```

Add Checkstyle

---

applications/generate/.pylintrc
applications/generate/philadelphia/java.py
applications/generate/philadelphia/model.py
applications/generate/philadelphia/quickfix.py
applications/generate/philadelphia/repository.py

Run [Pylint](https://www.pylint.org/) on Philadelphia Code Generator.

philadelphia-generate: Run Pylint

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageParser.java

Inlining parsing of BeginString(8), BodyLength(9), and CheckSum(10) tags makes message parsing 5.9% faster in the performance test when the incoming CheckSum(10) check is disabled and 6.1% faster when it is enabled.

philadelphia-core: Improve 'FIXMessageParser'

---

.github/workflows/test.yml

Improve GitHub Actions configuration

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java
libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessage.java
libraries/core/src/main/java/com/paritytrading/philadelphia/FIXMessageParser.java

Make it easier to construct a message container.

philadelphia-core: Add 'FIXMessage(FIXConfig)'

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java

philadelphia-core: Add 'FIXValue#asString(Appendable)'

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXValue.java
libraries/core/src/test/java/com/paritytrading/philadelphia/FIXValueTest.java
tests/perf-test/src/main/java/com/paritytrading/philadelphia/FIXValueBenchmark.java

philadelphia-core: Add 'FIXValue#contentEquals'

---

applications/generate/README.md
applications/generate/philadelphia/generate.py
applications/generate/philadelphia/orchestra.py
applications/generate/philadelphia/quickfix.py
applications/generate/philadelphia/repository.py
applications/generate/philadelphia/source.py
scripts/config-fix42.ini
scripts/config-fix43.ini
scripts/config-fix44.ini
scripts/config-fix50.ini
scripts/config-fix50sp1.ini
scripts/config-fix50sp2.ini
scripts/config-fixt11.ini
scripts/generate-repository

Remove the automatic configuration capability.

philadelphia-generate: Simplify FIX Repository input source

---

applications/generate/philadelphia/orchestra.py
applications/generate/philadelphia/quickfix.py
applications/generate/philadelphia/repository.py

In preparation of implementing new features to Philadelphia Code Generator, align and simplify the input sources.

philadelphia-generate: Clean up input sources

---

.github/workflows/java.yml
.github/workflows/python.yml

Run both Java and Python workflows if anything changes.

Clean up GitHub Actions configuration

---

libraries/fix42/pom.xml
libraries/fix43/pom.xml
libraries/fix44/pom.xml
libraries/fix50/pom.xml
libraries/fix50sp1/pom.xml
libraries/fix50sp2/pom.xml
libraries/fixlatest/pom.xml
libraries/fixt11/pom.xml
pom.xml

Fix the 'javadoc:aggregate' goal when running Maven on Java 17.

Improve 'maven-javadoc-plugin' configuration

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java

Rename `txMessage` to `adminMessage` to better reflect its usage.
Optimize memory footprint by setting the maximum number of fields in `adminMessage` to 8, which is the smallest possible value for it.

philadelphia-core: Improve 'FIXConnection'

---

applications/generate/philadelphia/orchestra.py

Remove a superfluous patch that is no longer needed for FIX Latest.

philadelphia-generate: Clean up FIX Orchestra support

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java
libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusHandler.java
libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusListener.java
libraries/core/src/test/java/com/paritytrading/philadelphia/FIXInitiatorTest.java

Improve handling of logon acknowledgements if msgSeqNum != rxMsgSeqNum

---

libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnectionStatusHandler.java

Use `inMsgSeqNum` and `outMsgSeqNum` for consistency.

philadelphia-core: Clean up terminology

---

.github/workflows/python.yml
applications/generate/README.md

`setup.py install` is deprecated.

philadelphia-generate: Update installation instructions
